variables:
  REPOSITORY: "cloudcare-forethought/cloudcare-forethought-setup"
  PROJECT: setup

stages:
  - build

buildProd:
  stage: build
  only:
    - /^release[\/-_]?.*$/
  script:
    - docker build -t $REPOSITORY:$CI_COMMIT_REF_SLUG .
    - docker tag $REPOSITORY:$CI_COMMIT_REF_SLUG registry.jiagouyun.com/$REPOSITORY:$CI_COMMIT_REF_SLUG
    - docker tag $REPOSITORY:$CI_COMMIT_REF_SLUG registry.jiagouyun.com/$REPOSITORY:prod
    - docker push registry.jiagouyun.com/$REPOSITORY:$CI_COMMIT_REF_SLUG
    - docker push registry.jiagouyun.com/$REPOSITORY:prod
  tags:
    - cloudcare

buildTesting:
  stage: build
  only:
    - dev
  script:
    - docker build -t $REPOSITORY:testing .
    - docker tag $REPOSITORY:testing registry.jiagouyun.com/$REPOSITORY:testing
    - docker push registry.jiagouyun.com/$REPOSITORY:testing
  tags:
    - cloudcare

buildRTM:
  stage: build
  only:
    - /^rtm(_\d+)+$/
  script:
    - V=(${CI_COMMIT_REF_SLUG//-/ })
    - VDIR=v${V[3]}.${V[4]}.${V[5]}
    - REPO=dataflux/$VDIR
    - TAG=${PROJECT}-${CI_COMMIT_REF_SLUG}
    - docker build -t $REPO:$TAG .
    - docker tag $REPO:$TAG pubrepo.jiagouyun.com/$REPO:$TAG
    - docker push pubrepo.jiagouyun.com/$REPO:$TAG
  tags:
    - cloudcare
