variables:
  REPOSITORY: "cloudcare-forethought/cloudcare-forethought-setup"
  PROJECT: launcher

stages:
  - build
  - deploy

buildProd:
  stage: build
  only:
    - /^release[\/-_]?.*$/
    - /^pre[\/-_]?.*$/
  script:
    - docker buildx build --platform linux/arm64,linux/amd64 -t registry.jiagouyun.com/$REPOSITORY:$CI_COMMIT_REF_NAME . --push
  tags:
    - cloudcare-multiarch 

buildTesting:
  stage: build
  only:
    - dev
  script:
    - docker buildx build --platform linux/arm64,linux/amd64 -t pubrepo.jiagouyun.com/$REPOSITORY:testing . --push

  tags:
    - cloudcare-multiarch 

buildBasis:
  stage: build
  only:
    - /^basis[\/-_]?.*$/
  script:
    - docker buildx build --platform linux/arm64,linux/amd64 -t registry.jiagouyun.com/basis/launcher-basis:v1.0 . -f ./basis.Dockerfile --push
  tags:
    - cloudcare-multiarch 

# buildTesting:
#   stage: build
#   only:
#     - dev
#   script:
#     - docker buildx build --platform linux/arm64,linux/amd64 -t pubrepo.jiagouyun.com/$REPOSITORY:testing . --push

#   tags:
#     - cloudcare-multiarch 

deployProd:
  stage: deploy
  only:
    - /^deploy_\d+$/
  script:
    - sh cd.sh -d
  tags:
    - cloudcare-multiarch 

buildRTM:
  stage: build
  only:
    - /\d+\.\d+\.\d+-\w+-\d+-prod/
  script:
    - V=(${CI_COMMIT_REF_NAME//[\.-]/ })
    - VDIR=${V[0]}.${V[1]}.${V[2]}
    - REPO=dataflux/$VDIR
    - TAG=${PROJECT}-${V[3]}-${V[4]}
    - docker buildx build --platform linux/arm64,linux/amd64 -t pubrepo.jiagouyun.com/$REPO:$TAG . --push
    - sed -e "s,{{repository}},pubrepo.jiagouyun.com/$REPO,g" charts/values.yaml > charts/launcher/values.yaml
    - helm package charts/launcher --version $VDIR --app-version $TAG
    - helm cm-push launcher-$VDIR.tgz launcher
    - rm -f launcher-$VDIR.tgz
    
  tags:
    - cloudcare-multiarch 

buildRTMPrev:
  stage: build
  only:
    - /\d+\.\d+\.\d+\.\d+-\w+-prev/
  script:
    - V=(${CI_COMMIT_REF_NAME//[\.-]/ })
    - VDIR=${V[0]}.${V[1]}.${V[2]}.${V[3]}
    - REPO=dataflux-prev/$VDIR
    - TAG=${PROJECT}-${V[4]}

    - docker buildx build --platform linux/arm64,linux/amd64 -t pubrepo.jiagouyun.com/$REPO:$TAG . --push
 
  tags:
    - cloudcare-multiarch 

