variables:
  REPOSITORY: "cloudcare-forethought/cloudcare-forethought-setup"
  PROJECT: setup

stages:
  - build

buildProd:
  stage: build
  only:
    - /^release[\/-_]?.*$/
    - /^pre[\/-_]?.*$/
  script:
    - docker build -t $REPOSITORY:$CI_COMMIT_REF_NAME .
    - docker tag $REPOSITORY:$CI_COMMIT_REF_NAME registry.jiagouyun.com/$REPOSITORY:$CI_COMMIT_REF_NAME
    - docker tag $REPOSITORY:$CI_COMMIT_REF_NAME registry.jiagouyun.com/$REPOSITORY:prod
    - docker push registry.jiagouyun.com/$REPOSITORY:$CI_COMMIT_REF_NAME
    - docker push registry.jiagouyun.com/$REPOSITORY:prod
  tags:
    - cloudcare

buildTesting:
  stage: build
  only:
    - dev
  script:
    - docker build -t $REPOSITORY:testing .
    - docker tag $REPOSITORY:testing registry.jiagouyun.com/$REPOSITORY:testing
    - docker push registry.jiagouyun.com/$REPOSITORY:testing
  tags:
    - cloudcare

buildRTM:
  stage: build
  only:
    - /^rtm(_\d+)+$/
  script:
    - V=(${CI_COMMIT_REF_NAME//_/ })
    - VDIR=v${V[1]}.${V[2]}.${V[3]}.${V[4]}
    - REPO=dataflux/$VDIR
    - TAG=${PROJECT}_rc_${V[5]}_${V[6]}
    - docker build -t $REPO:$TAG .
    - docker tag $REPO:$TAG pubrepo.jiagouyun.com/$REPO:$TAG
    - docker push pubrepo.jiagouyun.com/$REPO:$TAG
  tags:
    - cloudcare