# 报错告警所使用的环境名
envName: DataFlux

protocol: "https"
hostname: "{{'deploy-' if __common__.debug}}console.{{ other.domain }}"

database:
    # 测试环境容器外使用地址
    connection: "mysql+pymysql://{{core.dbInfo.dbUser}}:{{core.dbInfo.dbUserPassword}}@{{mysql.host}}:{{mysql.port}}/{{core.dbInfo.dbName}}?charset=utf8"
    pool_size: 50
    max_overflow: 10
    echo: false

kodo:
  host: kodo-inner.forethought-kodo.svc.cluster.local
  port: 9527
  timeout: 60
  installCmd: 'DW_TOKEN={token}  DW_UUID={agent_uuid} DW_AK={ak}  DW_SK={sk} bash -c "$(curl https://static.dataflux.cn/dataway/install.sh)"'
  upgradeCmd: 'DW_TOKEN={token}  DW_UUID={agent_uuid} DW_AK={ak}  DW_SK={sk} DW_UPGRADE=1  bash -c "$(curl https://static.dataflux.cn/dataway/install.sh)"'
  versionUrl: "https://static.dataflux.cn/dataway/version"

# 报警机器人
robot:
  url: 

# Cache
redis:
  # 内网
  host: {{redis.host}}
  port: {{redis.port}}
  db: 1
  password: {{redis.password}}
  max_connections: 100

# inner app 回调临时地址
inner_app_webhook_url: http://trigger.forethought-inner-app.svc.cluster.local:9000/api/v1/trigger/webhook

# 告警日志回调地址
alert_callback_url: http://front-backend.forethought-core.svc.cluster.local:5000/api/v1/front/webhooks/workspace/{}/rule/{}/type/{}/forward_to

secret:
  frontAuth: {{(core.secret or {}).frontAuth}}
  manageAuth: {{(core.secret or {}).manageAuth}}


# 默认邀请配置
invitation_set:
  enable: false
  invite_url: 
  title: "工作空间邀请"
  method:
    - email

# 消息服务
message_desk_set:
  enable: true
  use_https: true
  host: "message-desk.cloudcare.cn"
  port: 443
  timeout: 10
  ak_enable: false
  ak_id: 
  ak_secret: 

celery:
  name: "Celery"
  celery_broker_db: 2
  celery_result_db: 3
  cron_task:
    cron_notification:
      minute: '*/30'  

integration:
  domain: "https://integration.{{ other.domain }}"
  aliyunOSS:
    bucket: "prod-ft-integration"
    accessKeyId: ""
    secretAccessKey: ""
    endpoint: 'http://oss-cn-hangzhou.aliyuncs.com'
    rootFolder: "/"
  typeDict:
    collector:
      name: "采集器"
    dashboard:
      name: "视图模板"
    datasource:
      name: "数据源"
    scene:
      name: "场景模板"
