# 报错告警所使用的环境名
envName: DataFlux
isInternalAuth: true

protocol: {{ "http" if other.tls.tlsDisabled else "https"}}
hostname: "{{ domain.subDomain.console }}.{{ domain.domain }}"

database:
    # 测试环境容器外使用地址
    connection: "mysql+pymysql://{{mysql.core.user}}:{{mysql.core.password}}@{{mysql.base.host}}:{{mysql.base.port}}/{{mysql.core.database}}?charset=utf8mb4"
    pool_size: 50
    max_overflow: 10
    echo: false

# Elasticsearch Server 配置
ElasticsearchServer:
  protocol: {{ 'https' if elasticsearch.ssl else 'http' }}
  host: {{ elasticsearch.host }}
  port: {{ elasticsearch.port }}
  user: {{ elasticsearch.user }}
  password: {{ elasticsearch.password }}
  timeout: 30

kodo:
  host: kodo-inner.forethought-kodo
  port: 9527
  timeout: 60
  installCmd: 'DW_KODO={{ "http" if other.tls.tlsDisabled else "https"}}://{{ domain.subDomain.kodo }}.{{ domain.domain }} DW_KODO_WS={{ "ws" if other.tls.tlsDisabled else "wss"}}://{{ domain.subDomain.kodo }}.{{ domain.domain }} DW_TOKEN={token}  DW_UUID={agent_uuid} DW_AK={ak}  DW_SK={sk} bash -c "$(curl https://static.guance.com/dataway/install.sh)"'
  upgradeCmd: 'DW_KODO={{ "http" if other.tls.tlsDisabled else "https"}}://{{ domain.subDomain.kodo }}.{{ domain.domain }} DW_KODO_WS={{ "ws" if other.tls.tlsDisabled else "wss"}}://{{ domain.subDomain.kodo }}.{{ domain.domain }} DW_TOKEN={token}  DW_UUID={agent_uuid} DW_AK={ak}  DW_SK={sk} DW_UPGRADE=1  bash -c "$(curl https://static.guance.com/dataway/install.sh)"'
  versionUrl: "https://static.guance.com/dataway/version"
  datakitVersionUrl: "https://static.guance.com/datakit/version"

# 报警机器人
robot:
  url: 

# Cache
redis:
  # 内网
  host: {{redis.host}}
  port: {{redis.port}}
  db: 1
  password: {{redis.password}}
  max_connections: 100

# inner app 回调临时地址
inner_app_webhook_url: http://trigger.forethought-inner-app:9000/api/v1/trigger/webhook

# 告警日志回调地址
alert_callback_url: http://front-backend.forethought-core:5000/api/v1/webhooks/workspace/{}/rule/{}/type/{}/forward_to

secret:
  frontAuth: {{ (other.core.secret or {}).frontAuth}}
  manageAuth: {{ (other.core.secret or {}).manageAuth}}
  shareAuth:  {{ (other.core.secret or {}).shareAuth}}
  encryptKey: {{ (other.core.secret or {}).encryptKey }}

# 默认邀请配置
invitation_set:
  enable: false
  invite_url: {{ "http" if other.tls.tlsDisabled else "https"}}://auth.{{ domain.domain }}/join/workspace?uuid={}
  sender: DataFlux
  title: "工作空间邀请"
  method:
    - email

# 消息服务
message_desk_set:
  enable: true
  use_https: false
  host: "message-desk.middleware"
  port: 8088
  timeout: 10
  ak_enable: false
  ak_id: 
  ak_secret: 

celery:
  name: "Celery"
  celery_broker_db: 2
  celery_result_db: 3
  cron_task:
    cron_notification:
      minute: '*/30'  

sysDatawaySet:
  defaultCfg:
    token: {{ (other.workspace or {}).token }}
    timeout: 3
    
staticResource:
  domain: {{ "http" if other.tls.tlsDisabled else "https"}}://{{ domain.subDomain.staticResource }}.{{ domain.domain }}

share_set:
  share_url: {{ "http" if other.tls.tlsDisabled else "https"}}://{{ domain.subDomain.consoleApi }}.{{ domain.domain }}/api/v1/auth-token/{share_code}/login?isAuth={is_auth}&?code={code}

# CloudCare 系统配置
# 部署版本暂时不使用此配置，可以不作修改
CloudCareServer:
  use_https: true
  port: 443
  host: "admin-portal.cloudcare.cn"
  ak_id: "{{ other.cc.ak }}"
  ak_secret: "{{ other.cc.sk }}"
  timeout: 30

# 云拨测服务
DialingServer:
  # 拨测服务中心的地址配置
  # 此处不需要修改
  use_https: true
  host: dflux-dial.guance.com
  port: 443
  timeout: 10

  # 此处需要向产品侧索取拨测服务的 AK
  # 每个部署版本一组 AK 信息
  ak_id: "{{ other.dial.ak }}"
  ak_secret: "{{ other.dial.sk }}"
  
  # 每个部署的版本有不同的 DataWay 地址
  # 用于将拨测数据打入到相应部署版本工作空间内
  # 只要修改 host，保留原样的 ?token={} 参数，格式不要修改
  open_dataway_url: "{{ other.dial.dataway_url }}?token={}"

