SECRET: {{ other.func.secret }}
LOG_LEVEL: WARNING
LOG_FILE_PATH: /tmp/dataflux-func.log
LOG_FILE_FORMAT: text
WEB_BASE_URL: {{ "http" if other.tls.tlsDisabled else "https"}}://{{ domain.subDomain.function }}.{{ domain.domain }}
WEB_BIND: 0.0.0.0
WEB_PORT: 8088

MYSQL_HOST: {{mysql.base.host}}
MYSQL_PORT: {{mysql.base.port}}
MYSQL_USER: {{mysql['dataflux-func'].user}}
MYSQL_PASSWORD: {{mysql['dataflux-func'].password}}
MYSQL_DATABASE: {{mysql['dataflux-func'].database}}

REDIS_HOST: {{redis.host}}
REDIS_PORT: {{redis.port}}
REDIS_DATABASE: 4
REDIS_PASSWORD: {{redis.password}}
REDIS_USE_TLS : false

MODE: prod

_DISABLE_SETUP: true
_DISABLE_DB_AUTO_BACKUP: true

CUSTOM_DF_STUDIO_INNER_API_BASE_URL: http://inner.forethought-core:5000

CUSTOM_BUILTIN_DF_DATAWAY_HOST: internal-dataway.utils
CUSTOM_BUILTIN_DF_DATAWAY_PORT: 9528

CUSTOM_BUILTIN_NSQ_HOST: nsqlookupd.middleware
CUSTOM_BUILTIN_NSQ_PORT: 4161

CUSTOM_MESSAGE_DESK_HOST: message-desk.middleware
CUSTOM_MESSAGE_DESK_PORT: 8088
CUSTOM_MESSAGE_DESK_AK_ID: 
CUSTOM_MESSAGE_DESK_AK_SECRET: 
CUSTOM_MESSAGE_DESK_USE_HTTPS: false
