ftDataProcessor:
  # 是否为公网部署，影响：
  # 1. 直接函数调用是否需要登录（公网部署时需要登录）
  # 2. 自动触发配置模块是否需要登录（公网部署时需要登录）
  # 3. /dp-doc 文档页面是否需要登录（公网部署时需要登录）
  isPublicDeployment: true

  # FT集群内部专用访问域名
  innerAPIBaseURL: http://func-inner.func:8088
  # FT集群外部使用域名
  publicAPIBaseURL: https://{{'deploy-' if __common__.debug}}{{ domain.subDomain.function }}.{{ domain.domain }}

mode: prod
deployName: 生产环境（公网）
deployNotice:
  type               : dingTalkRobotWebhook
  onLaunch           : 
  onUncaughtException: 

logger:
  level: WARNING

webServer:
  baseURL : https://{{'deploy-' if __common__.debug}}{{ domain.subDomain.function }}.{{ domain.domain }}
  bind    : 0.0.0.0
  port    : 8088

  secret: {{ other.func.secret }}

mysql:
  host    : {{mysql.base.host}}
  port    : {{mysql.base.port}}
  user    : {{mysql.func.user}}
  password: {{mysql.func.password}}
  database: {{mysql.func.database}}
  timezone: '+0:00'

redis:
  host    : {{redis.host}}
  port    : {{redis.port}}
  db      : 4
  password: {{redis.password}}

celery:
  broker:
    host    : {{redis.host}}
    port    : {{redis.port}}
    db      : 4
    password: {{redis.password}}
  resultBackend:
    host    : {{redis.host}}
    port    : {{redis.port}}
    db      : 4
    password: {{redis.password}}
