# dataway oerating parameters

uuid: agnt_internal_dataway_1

# 初始安装是默认工作空间的 token
token: {{ (other.workspace or {}).token }}
collect_second: 60

bind: "0.0.0.0:9528"

# 初始安装是默认工作空间的 ak、sk
access_key: ""
secret_key: ""

remote_host: http://kodo.forethought-kodo:9527

log: log
log_level: warning
gin_log: gin.log

cache_cfg:
    dir: cache

# routes config
routes_config:
  - name: default
    ak_open: false
    lua:

# batch config
batch_config:
  workers: 8
  batch_size: 100
  batch_interval: 5
  queue_size: 128

retag_configs: