database:
    db_dialect: mysql
    connection: {{core.dbInfo.dbUser}}:{{core.dbInfo.dbUserPassword}}@tcp({{mysql.host}}:{{mysql.port}})/{{core.dbInfo.dbName}}

redis:
    host: {{redis.host}}:{{redis.port}}
    password: {{redis.password}}
    db:  0

log:
    log_file: /logdata/log
    level: debug
    disable_json: false
    disable_long_file_name: false
    gin_log_file: /logdata/gin.log

global:
    enable_inner: false
    stats_on: 256
    listen: ":9527"
    workers: 8

influxdb:
    read_timeout: 30000
    write_timeout: 500
    alert_rp: "rp_8760h"

nsq:
    lookupd: "http://nsqlookupd.middleware:4161"