database:
    db_dialect: mysql
    connection: {{mysql.core.user}}:{{mysql.core.password}}@tcp({{mysql.base.host}}:{{mysql.base.port}})/{{mysql.core.database}}

redis:
    host: {{redis.host}}:{{redis.port}}
    password: {{redis.password}}
    db:  0
    tls: false

log:
    log_file: /logdata/log
    level: warning
    json_format: false
    disable_long_file_name: false
    gin_log_file: /logdata/gin.log

global:
    enable_inner_api: true
    stats_on: 256
    listen: ":9527"
    workers: 16
    dataway: "http://internal-dataway.utils:9528"
    sys_ws_uuid: "wksp_system"

influxdb:
    read_timeout: 30
    write_timeout: 30
    enable_gz: true

# 未配置 host，或配置错误，表示不启用 ClickHouse 数仓功能
ck:
    # clickhouse host + tcp port 3306
    host: ""

    # clickhouse user name
    user: ""

    # clickhouse user password
    password: "" 

    # clickhouse read timeout set
    read_timeout: 30

    # clickhouse write timeout set 
    write_timeout: 30   

    # clickhouse cluster name 
    cluster_name: "default"

secret:
    encrypt_key: {{ (other.core.secret or {}).encryptKey }}

func:
    host: "http://server-inner.func2:8088"
    enable: true

es:
    host: {{'https' if elasticsearch.ssl else 'http'}}://{{elasticsearch.host}}:{{elasticsearch.port}}
    user: {{elasticsearch.user}}
    password: {{elasticsearch.password}}
    enable: true

nsq:
    lookupd: http://nsqlookupd.middleware:4161
