database:
    db_dialect: mysql
    connection: {{mysql.core.user}}:{{mysql.core.password}}@tcp({{mysql.base.host}}:{{mysql.base.port}})/{{mysql.core.database}}

redis:
    host: {{redis.host}}:{{redis.port}}
    password: "{{redis.password}}"
    db:  0
    tls: false

log:
    log_file: /logdata/log
    level: info
    json_format: false
    disable_long_file_name: false
    gin_log_file: /logdata/gin.log

global:
    enable_inner_api: false
    stats_on: 256
    listen: ":9527"
    workers: 8
    dataway: "http://internal-dataway.utils:9528"
    sys_ws_uuid: "wksp_system"

influxdb:
    read_timeout: 30
    write_timeout: 30
    enable_gz: true

func:
    host: "http://server-inner.func2:8088"
    enable: true

secret:
    encrypt_key: {{ (other.core.secret or {}).encryptKey }}

es:
    host: {{'https' if elasticsearch.ssl else 'http'}}://{{elasticsearch.host}}:{{elasticsearch.port}}
    user: {{elasticsearch.user}}
    password: "{{elasticsearch.password}}"
    enable: true

nsq:
    lookupd: http://nsqlookupd.middleware:4161

cc:
  ak: ""
  sk: ""
  syncBillExpired: "7d"
  syncBillHost: "https://boss.guance.com"
  postTime: "01:00"


# 新增配置项，用于 profile 数据的磁盘存储
profile:
  data_path: /data/profile

# 新增配置项，按照时序、日志分离查询worker
dql:
  metric_query_workers: 8 # 时序数据worker数量，默认值为8
  log_query_workers: 8 # 日志数据worker数量，默认值为8
# 新增配置项，调用inner的host
inner:
  host: "http://inner.forethought-core:5000"
