mysql:
  host    : {{mysql.host}}
  port    : {{mysql.port}}

  core:
    user    : {{core.dbInfo.dbUser}}
    password: {{core.dbInfo.dbUserPassword}}
    database: {{core.dbInfo.dbName}}

  func:
    user    : {{func.dbInfo.dbUser}}
    password: {{func.dbInfo.dbUserPassword}}
    database: {{func.dbInfo.dbName}}

  messageDesk:
    user    : {{messageDesk.dbInfo.dbUser}}
    password: {{messageDesk.dbInfo.dbUserPassword}}
    database: {{messageDesk.dbInfo.dbName}}

redis:
  host    : {{redis.host}}
  port    : {{redis.port}}
  password: {{redis.password}}

influxdb:
{% for item in influxdb %}
- host    : {{ item.host }}
  port    : {{ item.port }}
  username: {{ item.username }}
  password: {{ item.password }}
  ssl     : {{ item.ssl }}
{% endfor %}

domain:
  domain: {{ other.domain }}
  subDomain:
    console       : {{ other.subDomain.console }}
    consoleApi    : {{ other.subDomain.consoleApi }}
    management    : {{ other.subDomain.management }}
    managementApi : {{ other.subDomain.managementApi }}
    websocket     : {{ other.subDomain.websocket }}
    function      : {{ other.subDomain.function }}
    kodo          : {{ other.subDomain.kodo }}
    integration   : {{ other.subDomain.integration }}
