mode: prod
deployName: 【生产环境】

logger:
  level: WARNING

mysql:
  host    : {{mysql.host}}
  port    : {{mysql.port}}
  user    : {{messageDesk.dbInfo.dbUser}}
  password: {{messageDesk.dbInfo.dbUserPassword}}
  database: {{messageDesk.dbInfo.dbName}}
  timezone: '+0:00'

redis:
  host    : {{redis.host}}
  port    : {{redis.port}}
  db      : 5
  password: {{redis.password}}

celery:
  broker:
    host    : {{redis.host}}
    port    : {{redis.port}}
    db      : 5
    password: {{redis.password}}

  resultBackend:
    host    : {{redis.host}}
    port    : {{redis.port}}
    db      : 5
    password: {{redis.password}}
