# 生产环境
celery:
  brokerURL       : redis://:{{redis.password}}@{{redis.host}}:{{redis.port}}/5
  resultBackendURL: redis://:{{redis.password}}@{{redis.host}}:{{redis.port}}/5

logger:
  level: WARNING

redis:
  host    : '{{redis.host}}'
  port    : {{redis.port}}
  db      : 5
  password: {{redis.password}}

mysql:
  host    : {{mysql.base.host}}
  port    : {{mysql.base.port}}
  user    : {{mysql.messageDesk.user}}
  password: {{mysql.messageDesk.password}}
  database: {{mysql.messageDesk.database}}

# 短信服务的配置
aliyun:
  akId      : 
  akSecret  : 
  regionId  : cn-hangzhou
  showNumber: 

  userAgentTemplate: '{defaultUserAgent} vendor/zhuyun-dataflux@1.1'

# 邮件服务
mail:
  host        : smtpdm.aliyun.com
  port        : 465
  useSSL      : True
  usePlainAuth: True
  sender:
    DataFlux:
      from        : 'DataFlux <noreply@message.{{ domain.domain }}>'
      user        : noreply@message.{{ domain.domain }}
      password    : 
