mode: prod
deployName: 【生产环境】

logger:
  level: WARNING

mysql:
  host    : {{mysql.base.host}}
  port    : {{mysql.base.port}}
  user    : {{mysql.messageDesk.user}}
  password: {{mysql.messageDesk.password}}
  database: {{mysql.messageDesk.database}}
  timezone: '+0:00'

redis:
  host    : {{redis.host}}
  port    : {{redis.port}}
  db      : 5
  password: {{redis.password}}

celery:
  broker:
    host    : {{redis.host}}
    port    : {{redis.port}}
    db      : 5
    password: {{redis.password}}

  resultBackend:
    host    : {{redis.host}}
    port    : {{redis.port}}
    db      : 5
    password: {{redis.password}}

messageDesk:
  putTaskRequireSignIn: false