apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-func-func-worker-batch-builtin
  name: func-worker-batch-builtin
  namespace: func
spec:
  replicas: {{ config.replicas }}
  selector:
    matchLabels:
      app: deployment-func-func-worker-batch-builtin
  template:
    metadata:
      labels:
        app: deployment-func-func-worker-batch-builtin
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - deployment-func-func-worker-batch-builtin
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - ./run-by-queue.sh
        - runnerOnBatchBuiltin
        env:
        - name: FT_DATA_PROCESSOR_WORKER_CONFIG
          value: /func-worker-config.yaml
        image: {{ config.fullImagePath }}
        imagePullPolicy: IfNotPresent
        name: func-worker-batch-builtin
        resources: {}
        volumeMounts:
        - mountPath: /func-worker-config.yaml
          name: func-worker-config
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - configMap:
          defaultMode: 292
          name: func-worker-config
          optional: false
        name: func-worker-config

---

apiVersion: v1
kind: Service
metadata:
  name: func-worker-batch-builtin
  namespace: func
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    app: deployment-func-func-worker-batch-builtin
  type: ClusterIP
