apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-forethought-webclient-management-webclient
  name: management-webclient
  namespace: forethought-webclient
spec:
  replicas: {{ config.replicas }}
  selector:
    matchLabels:
      app: deployment-forethought-webclient-management-webclient
  template:
    metadata:
      labels:
        app: deployment-forethought-webclient-management-webclient
    spec:
      containers:
      - image: {{ config.fullImagePath }}
        imagePullPolicy: IfNotPresent
        name: management-webclient
        ports:
        - containerPort: 80
          name: 80tcp02
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: management-nginx-config
        - mountPath: /config/cloudcare-forethought-webmanage/config/config.json
          name: management-web-config
          subPath: config.json
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 292
          name: management-web-config
          optional: false
        name: management-web-config
      - configMap:
          defaultMode: 292
          name: management-nginx-config
          optional: false
        name: management-nginx-config

---

apiVersion: v1
kind: Service
metadata:
  name: management-webclient
  namespace: forethought-webclient
spec:
  ports:
  - name: 80tcp02
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deployment-forethought-webclient-management-webclient
  type: ClusterIP
