apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-forethought-kodo-kodo
  name: kodo
  namespace: forethought-kodo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-forethought-kodo-kodo
  template:
    metadata:
      labels:
        app: deployment-forethought-kodo-kodo
    spec:
      containers:
      - args:
        - sh
        - /kodo/prod.run.sh
        env:
        - name: KODO_INFLUX_WRITE_TIMEOUT_MS
          value: "500"
        - name: KODO_WORKERS
          value: "8"
        image: registry.jiagouyun.com/kodo/kodo:release-20191209
        imagePullPolicy: IfNotPresent
        name: kodo
        ports:
        - containerPort: 9527
          name: test 
          protocol: TCP
        volumeMounts:
        - mountPath: /kodo/config/config.yaml
          name: kodo
          subPath: config.yaml
        - mountPath: /logdata
          name: kodo-logs
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always
      volumes:
      - name: kodo-logs
        persistentVolumeClaim:
          claimName: kodo-logs
      - configMap:
          defaultMode: 420
          name: kodo
          optional: false
        name: kodo

---

apiVersion: v1
kind: Service
metadata:
  name: kodo
  namespace: forethought-kodo
spec:
  ports:
  - name: 9527tcp95272
    port: 9527
    protocol: TCP
    targetPort: 9527
  selector:
    app: deployment-forethought-kodo-kodo
  type: ClusterIP
