apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-func2-worker-beat
  name: worker-beat
  namespace: func2
spec:
  replicas: {{ config.replicas }}
  selector:
    matchLabels:
      app: deployment-func2-worker-beat
  template:
    metadata:
      labels:
        app: deployment-func2-worker-beat
    spec:
      containers:
      - args:
        - ./run-beat.sh
        image: {{ config.fullImagePath }}
        imagePullPolicy: IfNotPresent
        name: worker-beat
        resources: {}
        volumeMounts:
        - mountPath: /data/user-config.yaml
          name: user-config
          subPath: user-config.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - configMap:
          defaultMode: 292
          name: user-config
          optional: false
        name: user-config

---

apiVersion: v1
kind: Service
metadata:
  name: worker-beat
  namespace: func2
spec:
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    app: deployment-func2-worker-beat
  type: ClusterIP
