apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-middleware-nsqd2
  name: nsqd2
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-middleware-nsqd2
  template:
    metadata:
      labels:
        app: deployment-middleware-nsqd2
    spec:
      containers:
      - args:
        - /nsqd
        - --broadcast-address=nsqd2.middleware
        - --lookupd-tcp-address=nsqlookupd:4160
        - --data-path=/data/nsqd
        - --msg-timeout
        - 30h
        image: {{ config.fullImagePath }}
        imagePullPolicy: IfNotPresent
        name: nsqd2
        ports:
        - containerPort: 4150
          name: 4150tcp02
          protocol: TCP
        - containerPort: 4151
          name: 4151tcp02
          protocol: TCP
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data/nsqd
          name: nsqd-data-2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nsqd-data-2
        persistentVolumeClaim:
          claimName: nsqd-data-2

---

apiVersion: v1
kind: Service
metadata:
  name: nsqd2
  namespace: middleware
spec:
  ports:
  - name: 4150tcp02
    port: 4150
    protocol: TCP
    targetPort: 4150
  - name: 4151tcp02
    port: 4151
    protocol: TCP
    targetPort: 4151
  selector:
    app: deployment-middleware-nsqd2
  sessionAffinity: None
  type: ClusterIP
