apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-utils-dialtesting
  name: dialtesting
  namespace: utils
spec:
  replicas: {{ config.replicas }}
  selector:
    matchLabels:
      app: deployment-utils-dialtesting
  template:
    metadata:
      labels:
        app: deployment-utils-dialtesting
    spec:
      containers:
        - args:
            - /kodo/dialtesting
            - '--cfg'
            - /kodo/config/config.yaml
          image: {{ config.fullImagePath }}
          imagePullPolicy: {{ settings.imagePullPolicy }}
          name: dialtesting
          ports:
            - containerPort: 9538
              name: 9538tcp2
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /kodo/config/config.yaml
              name: dialtesting
              subPath: config.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: dialtesting
            optional: false
          name: dialtesting

---

apiVersion: v1
kind: Service
metadata:
  name: dialtesting
  namespace: utils
spec:
  ports:
    - name: 9538tcp02
      port: 9538
      protocol: TCP
      targetPort: 9538
  selector:
    app: deployment-utils-dialtesting
  type: ClusterIP
