apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-middleware-nsqd3
  name: nsqd3
  namespace: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-middleware-nsqd3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deployment-middleware-nsqd3
    spec:
      containers:
      - args:
        - /nsqd
        - --broadcast-address=nsqd3.middleware
        - --lookupd-tcp-address=nsqlookupd:4160
        - --data-path=/data/nsqd
        - --max-msg-size
        - "104857600"
        - --mem-queue-size
        - "3000"
        - --msg-timeout
        - 30h
        image: {{ config.fullImagePath }}
        imagePullPolicy: {{ settings.imagePullPolicy }}
        name: nsqd3
        ports:
        - containerPort: 4150
          name: 4150tcp02
          protocol: TCP
        - containerPort: 4151
          name: 4151tcp02
          protocol: TCP
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data/nsqd
          name: nsqd-data-3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nsqd-data-3
        persistentVolumeClaim:
          claimName: nsqd-data-3

---

apiVersion: v1
kind: Service
metadata:
  name: nsqd3
  namespace: middleware
spec:
  ports:
  - name: 4150tcp02
    port: 4150
    protocol: TCP
    targetPort: 4150
  - name: 4151tcp02
    port: 4151
    protocol: TCP
    targetPort: 4151
  selector:
    app: deployment-middleware-nsqd3
  sessionAffinity: None
  type: ClusterIP
