apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-forethought-kodo-python-pprof-parser
  name: python-pprof-parser
  namespace: forethought-kodo
spec:
  progressDeadlineSeconds: 600
  replicas: {{ config.replicas }}
  selector:
    matchLabels:
      app: deployment-forethought-kodo-python-pprof-parser
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-forethought-kodo-python-pprof-parser
    spec:
      containers:
      - image: {{ config.fullImagePath }} 
        imagePullPolicy: IfNotPresent
        name: python-pprof-parser
        ports:
        - containerPort: 9634
          name: http-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/pprofparser/pprofparser.yaml
          name: python-pprof-parser
          subPath: config.yaml
        - mountPath: /data
          name: profiling-data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always
      volumes:
      - name: profiling-data
        persistentVolumeClaim:
          claimName: profiling-data
      - configMap:
          defaultMode: 420
          name: python-pprof-parser
        name: python-pprof-parser

---

apiVersion: v1
kind: Service
metadata:
  name: python-pprof-parser
  namespace: forethought-kodo
spec:
  ports:
  - name: http-port
    port: 9634
    protocol: TCP
    targetPort: 9634
  selector:
    app: deployment-forethought-kodo-python-pprof-parser
  sessionAffinity: None
  type: ClusterIP
