apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-func-func-inner
  name: func-inner
  namespace: func
spec:
  replicas: {{ config.replicas }}
  selector:
    matchLabels:
      app: deployment-func-func-inner
  template:
    metadata:
      labels:
        app: deployment-func-func-inner
    spec:
      containers:
      - env:
        - name: FT_DATA_PROCESSOR_CONFIG
          value: /func-inner-config.yaml
        image: {{ config.fullImagePath }}
        imagePullPolicy: IfNotPresent
        name: func-inner
        ports:
        - containerPort: 8088
          name: 8088tcp80882
          protocol: TCP
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /func-inner-config.yaml
          name: func-inner-config
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-key
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 292
          name: func-inner-config
          optional: false
        name: func-inner-config

---

apiVersion: v1
kind: Service
metadata:
  name: func-inner
  namespace: func
spec:
  ports:
  - name: 8088tcp80882
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: deployment-func-func-inner
  type: ClusterIP
