apiVersion: v1
data:
  config.yaml: |-
{{ config.core | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: core
  namespace: forethought-core

---

apiVersion: v1
data:
  config.yaml: |-
{{ config.kodo | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: kodo
  namespace: forethought-kodo

---

apiVersion: v1
data:
  config.yaml: |-
{{ config.kodoInner | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: kodo-inner
  namespace: forethought-kodo

---

apiVersion: v1
data:
  kodo.conf: |-
{{ config.kodoNginx | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: kodo-nginx
  namespace: forethought-kodo

---

apiVersion: v1
data:
  config-api.yaml: |-
{{ config.messageDeskApi | indent(4) }}
  config-worker.yaml: |-
{{ config.messageDeskWorker | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: message-desk
  namespace: middleware

---

apiVersion: v1
data:
  config.js: |-
{{ config.frontWeb | indent(4) }}
  nginx.conf: |-
{{ config.frontNginx | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: front-web-config
  namespace: forethought-webclient

---

apiVersion: v1
data:
  config.json: |-
{{ config.managementWeb | indent(4) }}
  nginx.conf: |-
{{ config.managementNginx | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: management-web-config
  namespace: forethought-webclient

---

apiVersion: v1
data:
  config.yaml: |-
{{ config.func | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: func-config
  namespace: func

---

apiVersion: v1
data:
  config.yaml: |-
{{ config.funcInner | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: func-inner-config
  namespace: func

---

apiVersion: v1
data:
  config.yaml: |-
{{ config.funcWorker | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: func-worker-config
  namespace: func


---

apiVersion: v1
data:
  app.ini: |-
{{ config.innerAppTrigger | indent(4) }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: trigger-conf
  namespace: forethought-inner-app
