{% for item in config %}
apiVersion: v1
data:
  {{ item.mapkey }}: |-
{{ item.content | indent(4) }}
kind: ConfigMap
metadata:
  name: {{ item.mapname }}
  namespace: {{ item.namespace }}

{% if not loop.last %}
--- 
{% endif %}

{% endfor %}
