apiVersion: v1
kind: Namespace
metadata:
  name: forethought-core

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: forethought-inner-app

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: forethought-webclient

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: forethought-kodo

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: func

--- 

apiVersion: v1
kind: Namespace
metadata:
  name: middleware

