apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cattle.io/creator: norman
  name: ft-sysconfig
  namespace: forethought-core
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ storageClassName }}
  volumeMode: Filesystem


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cattle.io/creator: norman
  name: kodo-logs
  namespace: forethought-kodo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ storageClassName }}
  volumeMode: Filesystem


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cattle.io/creator: norman
  name: kodo-inner-logs
  namespace: forethought-kodo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ storageClassName }}
  volumeMode: Filesystem


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cattle.io/creator: norman
  name: message-desk-logs
  namespace: middleware
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ storageClassName }}
  volumeMode: Filesystem


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cattle.io/creator: norman
  name: message-desk-worker-logs
  namespace: middleware
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ storageClassName }}
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nsqd-data-1
  namespace: middleware
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: {{ storageClassName }}
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kapacitor-data-01
  namespace: middleware
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ storageClassName }}
  volumeMode: Filesystem
