{% for pvc in pvcs %}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ pvc.name }}
  namespace: {{ pvc.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ pvc.storage }}
  storageClassName: {{ storageClassName }}
  volumeMode: Filesystem

{% if not loop.last %}
--- 
{% endif %}

{% endfor %}