{{- if .Values.ingress.enabled -}}
{{- $fullName := include "launcher.fullname" . -}}
{{- $hostName := .Values.ingress.hostName -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ template "launcher.fullname" . }}"
  labels:
    {{- include "launcher.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
#    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ $hostName | quote }}
      secretName: .Values.ingress.tls
#    {{- end }}
  {{- end }}
  rules:
    - host: {{ $hostName | quote }}
      http:
        paths:
          - path: /
            {{- if and "ImplementationSpecific" (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: "{{ template "launcher.fullname" . }}"
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: "{{ template "launcher.fullname" . }}"
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
