---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ template "launcher.fullname" . }}"
  template:
    metadata:
      labels:
        app: "{{ template "launcher.fullname" . }}"
    spec:
      containers:
      - args:
        - python
        - web.py
        image: {{ .Values.image.repository }}:{{  .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: launcher
        ports:
        - containerPort: 5000
          name: 5000tcp01
          protocol: TCP
        resources: {}
        securityContext:
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/cloudcare-forethought-setup/persistent-data
          name: persistent-data
        - mountPath: /config/cloudcare-forethought-setup/config/settings.yaml
          name: settings
          subPath: settings.yaml
        workingDir: /config/cloudcare-forethought-setup
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: launcher
      serviceAccountName: launcher      
      volumes:
      - name: persistent-data
        persistentVolumeClaim:
          claimName: persistent-data
      - configMap:
          defaultMode: 256
          name: launcher-settings
          optional: false
        name: settings

  

