apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: forethought-setup
  namespace: forethought-core
spec:
  ports:
  - name: 8080tcp105621-forethought-setup
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    workload.user.cattle.io/workloadselector: deployment-cloudcare-forethought-forethought-setup
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-cloudcare-forethought-forethought-setup
  name: forethought-setup
  namespace: forethought-core
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-cloudcare-forethought-forethought-setup
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-cloudcare-forethought-forethought-setup
    spec:
      containers:
      - args:
        - python
        - web.py
        image: {{ imagePath }}
        imagePullPolicy: Always
        name: forethought-setup
        ports:
        - containerPort: 5000
          name: 5000tcp10562
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        workingDir: /config/cloudcare-forethought-setup
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dc-c5pr6
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
