apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: websocket
  namespace: forethought-core
spec:
  ports:
  - name: 5000tcp105511-forethought-backend
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    workload.user.cattle.io/workloadselector: deployment-cloudcare-forethought-forethought-backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-cloudcare-forethought-forethought-backend
  name: websocket
  namespace: forethought-core
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-cloudcare-forethought-forethought-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-cloudcare-forethought-forethought-backend
    spec:
      containers:
      - args:
        - bash
        - run.sh
        image: {{ config.imagePath }}
        imagePullPolicy: Always
        name: forethought-backend
        ports:
        - containerPort: 5000
          name: 5000tcp105511
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config/cloudcare-forethought-backend/config/config.yaml
          name: ft-backend-config
          subPath: config.yaml
        workingDir: /config/cloudcare-forethought-backend
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dc-c5pr6
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          name: ft-backend-config
          optional: false
        name: ft-backend-config
status: {}
