debug: False

namespaces:
  - forethought-core
  - forethought-inner-app
  - forethought-webclient
  - forethought-kodo
  - func
  - middleware

services:
  - namespace: forethought-core
    services:
    - key: management-backend
      name: 后台管理平台 API
      image: core
      replicas: 2

    - key: inner
      name: Inner API
      image: core
      replicas: 2

    - key: front-backend
      name: 用户前台 API
      image: core
      replicas: 2

    - key: integration-scanner
      name: 集成扫描 Worker
      image: core

    - key: websocket
      name: Websocket
      image: core
      replicas: 2

  - namespace: forethought-inner-app
    services:
    - key: trigger
      name: 通知触发器
      image: trigger

  - namespace: forethought-webclient
    services:
    - key: management-webclient
      name: 管理后台前端
      image: management-webclient

    - key: front-webclient
      name: 用户前台前端
      image: front-webclient

  - namespace: forethought-kodo
    services:
    - key: kodo
      name: Kodo
      image: kodo

    - key: kodo-inner
      name: Kodo Inner
      image: kodo

    - key: kodo-nginx
      name: Kodo Nginx
      image: nginx

  - namespace: func
    services:
    - key: func
      name: 函数计算
      image: func
      replicas: 2

    - key: func-inner
      name: 函数计算 Inner
      image: func
      replicas: 2

    - key: func-worker-beat
      name: 函数计算 Worker Beat
      image: func-worker

    - key: func-worker-debugger
      name: 函数计算 Worker Debugger
      image: func-worker

    - key: func-worker-rpc-crontab
      name: 函数计算 Worker RPC
      image: func-worker
      replicas: 4

    - key: func-worker-utils
      name: 函数计算 Worker Utils
      image: func-worker
      replicas: 2

  - namespace: middleware
    services:
    - key: message-desk
      name: 消息中心 API
      image: message-desk

    - key: message-desk-worker
      name: 消息中心 Worker
      image: message-desk-worker

    - key: nsqadmin
      name: NSQ Admin
      image: nsq

    - key: nsqlookupd
      name: NSQ Lookupd
      image: nsq

    - key: nsqd
      name: NSQ Node
      image: nsq

    - key: kapacitor
      name: Kapacitor
      image: kapacitor

databases:
  core: df_core
  message_desk: df_message_desk
  func: df_func

influxDB:
  databases:
    - internal_alert
    - internal_baseline
    - internal_system
    - internal_keyevent

  replication: 
  - rpName: rp1
    duration: 24    # 1d

  - rpName: rp2
    duration: 168   # 7d

  - rpName: rp3
    duration: 720   # 30d

  - rpName: rp4
    duration: 4320  # 180d

  - rpName: rp5
    duration: 8760  # 365d
    default: True
