debug: False

tmpDir: /tmp/k8s

namespaces:
  - forethought-core
  - forethought-inner-app
  - forethought-webclient
  - forethought-kodo
  - func
  - middleware

services:
  - namespace: forethought-core
    services:
    - key: management-backend
      name: 后台管理平台 API
      image: core
      replicas: 2

    - key: inner
      name: Inner API
      image: core
      replicas: 2

    - key: front-backend
      name: 用户前台 API
      image: core
      replicas: 2

    - key: integration-scanner
      name: 集成扫描 Worker
      image: core

    - key: websocket
      name: Websocket
      image: core
      replicas: 2

    configmaps:
    - key: core
      services:
      - management-backend
      - inner
      - front-backend
      - integration-scanner
      - websocket
      file: forethought-backend.yaml

  - namespace: forethought-inner-app
    services:
    - key: trigger
      name: 通知触发器
      image: trigger

    configmaps:
    - key: innerAppTrigger
      services:
      - trigger
      file: inner-app-trigger-config.ini

  - namespace: forethought-webclient
    services:
    - key: management-webclient
      name: 管理后台前端
      image: management-webclient

    - key: front-webclient
      name: 用户前台前端
      image: front-webclient

    configmaps:
    - key: frontWeb
      services:
      - front-webclient
      file: front-web.js

    - key: frontNginx
      services:
      - front-webclient
      file: front-nginx.conf

    - key: managementWeb
      services:
      - management-webclient
      file: management-web.json

    - key: managementNginx
      services:
      - management-webclient
      file: management-nginx.conf

  - namespace: forethought-kodo
    services:
    - key: kodo
      name: Kodo
      image: kodo

    - key: kodo-inner
      name: Kodo Inner
      image: kodo

    - key: kodo-nginx
      name: Kodo Nginx
      image: nginx

    configmaps:
    - key: kodo
      services:
      - kodo
      file: kodo.yaml

    - key: kodoInner
      services:
      - kodo-inner
      file: kodo-inner.yaml

    - key: kodoNginx
      services:
      - kodo-nginx
      file: kodo-nginx.conf


  - namespace: func
    services:
    - key: func
      name: 函数计算
      image: func
      replicas: 2

    - key: func-inner
      name: 函数计算 Inner
      image: func
      replicas: 2

    - key: func-worker-beat
      name: 函数计算 Worker Beat
      image: func-worker

    - key: func-worker-debugger
      name: 函数计算 Worker Debugger
      image: func-worker

    - key: func-worker-rpc-crontab
      name: 函数计算 Worker RPC
      image: func-worker
      replicas: 4

    - key: func-worker-utils
      name: 函数计算 Worker Utils
      image: func-worker
      replicas: 2

    configmaps:
    - key: func
      services:
      - func
      file: func-config.yaml

    - key: funcInner
      services:
      - func-inner
      file: func-inner-config.yaml

    - key: funcWorker
      services:
      - func-worker-beat
      - func-worker-debugger
      - func-worker-rpc-crontab
      - func-worker-utils
      file: func-worker-config.yaml

  - namespace: middleware
    services:
    - key: message-desk
      name: 消息中心 API
      image: message-desk

    - key: message-desk-worker
      name: 消息中心 Worker
      image: message-desk-worker

    - key: nsqadmin
      name: NSQ Admin
      image: nsq

    - key: nsqlookupd
      name: NSQ Lookupd
      image: nsq

    - key: nsqd
      name: NSQ Node
      image: nsq

    - key: kapacitor
      name: Kapacitor
      image: kapacitor

    configmaps:
    - key: messageDeskApi
      services:
      - message-desk
      file: message-desk-api.yaml

    - key: messageDeskWorker
      services:
      - message-desk-worker
      file: message-desk-worker.yaml

databases:
  core: df_core
  message_desk: df_message_desk
  func: df_func

influxDB:
  databases:
    - internal_alert
    - internal_baseline
    - internal_system
    - internal_keyevent

  replication:
  - rpName: rp0
    duration: 24    # 1d

  - rpName: rp1
    duration: 168   # 7d

  - rpName: rp2
    duration: 720   # 30d

  - rpName: rp3
    duration: 2160  # 90d

  - rpName: rp4
    duration: 4320  # 180d
    default: True

  - rpName: rp5
    duration: 8760  # 365d

updates:
  - api: # http://inner.forethought-core:5000/api/v1/inner/upgrade/list
    namespace: forethought-core
    project: core
    noDatabase: False
    dataKey: content
    config:
      - key: core
        mapName: core
        mapKey: config.yaml

  - api: # http://inner.forethought-core:5000/api/v1/inner/upgrade/list
    namespace: forethought-inner-app
    project: trigger
    noDatabase: True
    dataKey: content
    config:
      - key: innerAppTrigger
        mapName: trigger-conf
        mapKey: app.ini

  - api: # http://kodo-inner.forethought-kodo:9527/api/v1/update-versions
    namespace: forethought-kodo
    project: kodo
    noDatabase: True
    dataKey: data
    config:
      - key: kodo
        mapName: kodo
        mapKey: config.yaml

      - key: kodoInner
        mapName: kodo-inner
        mapKey: config.yaml

      - key: kodoNginx
        mapName: kodo-nginx
        mapKey: kodo.conf

  - api: # http://inner.func:8088/api/v1/update-versions
    namespace: func
    project: func
    noDatabase: False
    dataKey: data
    config:
      - key: func
        mapName: func-config
        mapKey: config.yaml

      - key: funcInner
        mapName: func-inner-config
        mapKey: config.yaml

      - key: funcWorker
        mapName: func-worker-config
        mapKey: config.yaml

  - api: # http://message-desk.middleware:8088/api/v1/update-versions
    namespace: middleware
    project: messageDesk
    noDatabase: False
    dataKey: data
    config:
      - key: messageDeskApi
        mapName: message-desk
        mapKey: config.yaml

      - key: messageDeskWorker
        mapName: message-desk
        mapKey: config.yaml

