debug: False

tmpDir: /tmp/k8s

namespaces:
  - forethought-core
  - forethought-inner-app
  - forethought-webclient
  - forethought-kodo
  - func
  - middleware
  - utils

services:
  - namespace: forethought-core
    services:
    - key: management-backend
      name: 后台管理平台 API
      image: core
      replicas: 2

    - key: inner
      name: Inner API
      image: core
      replicas: 2

    - key: front-backend
      name: 用户前台 API
      image: core
      replicas: 2

    - key: integration-scanner
      name: 集成扫描 Worker
      image: core

    - key: websocket
      name: Websocket
      image: core
      replicas: 2

    configmaps:
    - key: core
      mapname: core
      mapkey: config.yaml
      services:
      - management-backend
      - inner
      - front-backend
      - integration-scanner
      - websocket
      template: forethought-backend.yaml

    pvcs:
    - name: ft-sysconfig
      storage: 10Gi

  - namespace: forethought-inner-app
    services:
    - key: trigger
      name: 通知触发器
      image: trigger

    configmaps:
    - key: innerAppTrigger
      mapname: trigger-conf
      mapkey: config.yaml
      services:
      - trigger
      template: inner-app-trigger-config.yaml

  - namespace: forethought-webclient
    services:
    - key: management-webclient
      name: 管理后台前端
      image: management-webclient

    - key: front-webclient
      name: 用户前台前端
      image: front-webclient

    configmaps:
    - key: frontWeb
      mapname: front-web-config
      mapkey: config.js
      services:
      - front-webclient
      template: front-web.js

    - key: frontNginx
      mapname: front-nginx-config
      mapkey: nginx.conf
      services:
      - front-webclient
      template: front-nginx.conf

    - key: managementWeb
      mapname: management-web-config
      mapkey: config.json
      services:
      - management-webclient
      template: management-web.json

    - key: managementNginx
      mapname: management-nginx-config
      mapkey: nginx.conf
      services:
      - management-webclient
      template: management-nginx.conf

  - namespace: forethought-kodo
    services:
    - key: kodo
      name: Kodo
      image: kodo

    - key: kodo-inner
      name: Kodo Inner
      image: kodo

    - key: kodo-nginx
      name: Kodo Nginx
      image: nginx

    configmaps:
    - key: kodo
      mapname: kodo
      mapkey: config.yaml
      services:
      - kodo
      template: kodo.yaml

    - key: kodoInner
      mapname: kodo-inner
      mapkey: config.yaml
      services:
      - kodo-inner
      template: kodo-inner.yaml

    - key: kodoNginx
      mapname: kodo-nginx
      mapkey: kodo.conf
      services:
      - kodo-nginx
      template: kodo-nginx.conf

    pvcs:
    - name: kodo-logs
      storage: 20Gi

    - name: kodo-inner-logs
      storage: 20Gi

  - namespace: func
    services:
    - key: func
      name: 函数计算
      image: func
      replicas: 2

    - key: func-inner
      name: 函数计算 Inner
      image: func
      replicas: 2

    - key: func-worker-beat
      name: 函数计算 Worker Beat
      image: func-worker

    - key: func-worker-debugger
      name: 函数计算 Worker Debugger
      image: func-worker

    - key: func-worker-rpc-crontab
      name: 函数计算 Worker RPC
      image: func-worker
      replicas: 4

    - key: func-worker-utils
      name: 函数计算 Worker Utils
      image: func-worker
      replicas: 2

    configmaps:
    - key: func
      mapname: func-config
      mapkey: config.yaml
      services:
      - func
      template: func-config.yaml

    - key: funcInner
      mapname: func-inner-config
      mapkey: config.yaml
      services:
      - func-inner
      template: func-inner-config.yaml

    - key: funcWorker
      mapname: func-worker-config
      mapkey: config.yaml
      services:
      - func-worker-beat
      - func-worker-debugger
      - func-worker-rpc-crontab
      - func-worker-utils
      template: func-worker-config.yaml

  - namespace: middleware
    services:
    - key: message-desk
      name: 消息中心 API
      image: message-desk

    - key: message-desk-worker
      name: 消息中心 Worker
      image: message-desk-worker

    - key: nsqadmin
      name: NSQ Admin
      image: nsq

    - key: nsqlookupd
      name: NSQ Lookupd
      image: nsq

    - key: nsqd
      name: NSQ Node
      image: nsq

    - key: nsqd2
      name: NSQ Node 02
      image: nsq

    - key: nsqd3
      name: NSQ Node 03
      image: nsq

    - key: kapacitor
      name: Kapacitor
      image: kapacitor

    - key: kapacitor02
      name: Kapacitor 02
      image: kapacitor

    configmaps:
    - key: messageDeskApi
      mapname: message-desk
      mapkey: config.yaml
      services:
      - message-desk
      template: message-desk-api.yaml

    - key: messageDeskWorker
      mapname: message-desk-worker
      mapkey: config.yaml
      services:
      - message-desk-worker
      template: message-desk-worker.yaml

    pvcs:
    - name: message-desk-logs
      storage: 20Gi

    - name: message-desk-worker-logs
      storage: 20Gi

    - name: nsqd-data-1
      storage: 40Gi

    - name: nsqd-data-2
      storage: 40Gi

    - name: nsqd-data-3
      storage: 40Gi

    - name: kapacitor-data-01
      storage: 40Gi

    - name: kapacitor-data-02
      storage: 40Gi

  - namespace: utils
    services:
    - key: utils-server
      name: 公共工具服务
      image: utils-server

    configmaps: []

databases:
  core: df_core
  message_desk: df_message_desk
  func: df_func

influxDB:
  databases:
    - internal_alert
    - internal_baseline
    - internal_system
    - internal_keyevent

  replication:
  - rpName: rp0
    duration: 24    # 1d

  - rpName: rp1
    duration: 168   # 7d

  - rpName: rp2
    duration: 720   # 30d

  - rpName: rp3
    duration: 2160  # 90d

  - rpName: rp4
    duration: 4320  # 180d
    default: True

  - rpName: rp5
    duration: 8760  # 365d

defaultSubdomain:
  console: dataflux
  consoleApi: df-api
  management: df-management
  managementApi: df-management-api
  websocket: df-websocket
  function: df-func
  kodo: df-kodo
  integration: df-integration

updates:
  - api: http://inner.forethought-core:5000/api/v1/inner/upgrade/list
    namespace: forethought-core
    project: core
    noDatabase: False
    dataKey: content
    config:
      - key: core
        mapName: core
        mapKey: config.yaml

  - api: http://trigger.forethought-inner-app:9000/api/v1/upgrade
    namespace: forethought-inner-app
    project: trigger
    noDatabase: True
    dataKey: data
    config:
      - key: innerAppTrigger
        mapName: trigger-conf
        mapKey: config.yaml

  - api: http://kodo-inner.forethought-kodo:9527/api/v1/app/update
    namespace: forethought-kodo
    project: kodo
    noDatabase: True
    dataKey: content
    config:
      - key: kodo
        mapName: kodo
        mapKey: config.yaml

      - key: kodoInner
        mapName: kodo-inner
        mapKey: config.yaml

      - key: kodoNginx
        mapName: kodo-nginx
        mapKey: kodo.conf

  - api: http://func-inner.func:8088/api/v1/upgrade-info
    namespace: func
    project: func
    noDatabase: False
    dataKey: data
    config:
      - key: func
        mapName: func-config
        mapKey: config.yaml

      - key: funcInner
        mapName: func-inner-config
        mapKey: config.yaml

      - key: funcWorker
        mapName: func-worker-config
        mapKey: config.yaml

  - api: http://message-desk.middleware:8088/api/v1/upgrade
    namespace: middleware
    project: messageDesk
    noDatabase: False
    dataKey: data
    config:
      - key: messageDeskApi
        mapName: message-desk
        mapKey: config.yaml

      - key: messageDeskWorker
        mapName: message-desk
        mapKey: config.yaml

