debug: True

namespaces:
  - forethought-core
  - forethought-inner-app
  - forethought-webclient
  - forethought-kodo
  - func
  - middleware

services:
  - key: management-backend
    name: 后台管理平台 API

  - key: inner
    name: Inner API

  - key: front-backend
    name: 用户前台 API

  - key: integration-scanner
    name: 集成扫描 Worker

  - key: websocket
    name: Websocket

  - key: management-webclient
    name: 管理后台前端

  - key: front-webclient
    name: 用户前台前端

  - key: kodo
    name: Kodo

  - key: kodo-inner
    name: Kodo Inner

  - key: kodo-nginx
    name: Kodo Nginx

  - key: message-desk
    name: 消息中心 API

  - key: message-desk-worker-beat
    name: 消息中心 Beat

  - key: message-desk-worker
    name: 消息中心 Worker

  - key: func
    name: 函数计算

  - key: func-inner
    name: 函数计算 Inner

  - key: func-worker-beat
    name: 函数计算 Worker Beat

  - key: func-worker-debugger
    name: 函数计算 Worker Debugger

  - key: func-worker-rpc-crontab
    name: 函数计算 Worker RPC

  - key: func-worker-utils
    name: 函数计算 Worker Utils

  - key: trigger
    name: 通知触发器

