mysql:
  host    : 172.16.0.43
  port    : 32306

  core:
    user    : df_core
    password: cjPxQLroQaSz
    database: df_core

  func:
    user    : df_func
    password: cFk66KwqjxGX
    database: df_func

  messageDesk:
    user    : df_message_desk
    password: c8uJsmFDNkXd
    database: df_message_desk

redis:
  host    : 172.16.0.43
  port    : 30397
  db      : 5
  password: viFRKZiZkoPmXnyF

influxdb:
  host    : 
  port    : 
  username: 
  password: 
  ssl     : 

domain:
  domain: dataflux.cn
  subDomain:
    console       : console
    consoleApi    : console-api
    management    : management
    managementApi : management-api
    websocket     : ws
    function      : func
    kodo          : kodo
    integration   : integration
